### ISSUE TITLE
bb broken with pyro (worked until morty)

### ISSUE THREAD

**Issue by RobertBerger** [kergoth/bb#34]
I was super happy with bb until morty, but moved to pyro and it seems to be broken now.
e.g.

```
~/test/bb/bin/bb show DISTRO
Traceback (most recent call last):
  File "/home/genius/test/bb/libexec/bb-show", line 202, in <module>
    bbcmd.run_main(main)
  File "/home/genius/test/bb/libexec/bbcmd.py", line 310, in run_main
    sys.exit(main(sys.argv[1:]) or 0)
  File "/home/genius/test/bb/libexec/bb-show", line 198, in main
    return show(args)
  File "/home/genius/test/bb/libexec/bb-show", line 158, in show
    tinfoil = bbcmd.Tinfoil(output=sys.stderr)
  File "/home/genius/test/bb/libexec/bbcmd.py", line 34, in __init__
    self.localdata = self.cooker.data
AttributeError: 'NoneType' object has no attribute 'data'

```
Is this what you meant with your comment that most of bb is broken due to Tinfoil?

I guess it's a major effort to rewrite bb. 
Is it dead?

**Comment by kergoth** [comment]
Yep, this is the same as issue #33. It's not a complete rewrite, but it's close to it, and has to be done for each individual sub-command one by one. I do intend to either fix it or get equivalent functionality into bitbake itself during the 2.4 timeframe, however, so it's not a lost cause, and clearly meets needs that just aren't satisfied by the existing official tools right now.

**Comment by RobertBerger** [comment]
Thanks for the reply. Please let me know when you have something to test for me. In the meantime I'll rewrite my scripts so they don't rely on bb, since I need to get something up and running soon with pyro.

Also some other things changed in pyro, like depexp was replaced by taskexp. I was hoping to find reverse dependencies with bb;)
